package:
  name: anaconda_prompt-split
  version: 1.0.0

build:
  number: 0
  # Only building this on Windows for now until
  # other platforms are fleshed out more.
  skip: True  # [not win]


outputs:
  - name: anaconda_prompt
    script: bld_win.bat    # [win]
    script: build_unix.sh  # [not win]
    requirements:
      run_constrained:
        - anaconda-navigator >=1.9.8
        - menuinst >=2.1.0
    test:
      commands:
        - IF NOT EXIST %PREFIX%\\anaconda_prompt_menu.json EXIT 1  # [win]
        - IF NOT EXIST %PREFIX%\\anaconda_prompt.ico EXIT 1        # [win]
        - test -f ${PREFIX}/anaconda_prompt_menu.json || exit 1    # [not win]
        - test -f ${PREFIX}/bin/anaconda_prompt  || exit 1         # [not win]
        - test -f ${PREFIX}/anaconda_prompt.icns || exit 1         # [osx]
        - test -f ${PREFIX}/anaconda_prompt.png || exit 1          # [linux]
    app:
      entry:
        start cmd.exe /K "${CONDA_ROOT_PREFIX}\\Scripts\\activate.bat" "${CONDA_PREFIX}"  # [win]
      summary: Anaconda Prompt
      icon: anaconda_prompt.png
  - name: anaconda_powershell_prompt
    skip: True  # [not win]
    script: bld_win.bat
    requirements:
      run_constrained:
        - anaconda-navigator >=1.9.8
        - menuinst >=2.1.0
    test:
      commands:
        - IF NOT EXIST %PREFIX%\\anaconda_powershell_prompt_menu.json EXIT 1
        - IF NOT EXIST %PREFIX%\\anaconda_powershell_prompt.ico EXIT 1
    app:
      entry:
        start powershell.exe -ExecutionPolicy ByPass -NoExit -Command  "& '{CONDA_ROOT_PREFIX}\\shell\\condabin\\conda-hook.ps1' ; conda activate '{CONDA_PREFIX}'"
      summary: Anaconda Powershell Prompt
      icon: anaconda_prompt_powershell.png
      type: desk

about:
  description: |
    Package to create shortcuts for terminals that open with an activated conda environment.
  license: BSD-3-Clause
  license_family: BSD
  license_url: https://github.com/AnacondaRecipes/anaconda_prompt-feedstock/blob/main/LICENSE
  summary: Terminal shortcut creator for Anaconda
  home: https://github.com/AnacondaRecipes/anaconda_prompt-feedstock
  dev_url: https://github.com/AnacondaRecipes/anaconda_prompt-feedstock
  doc_url: https://github.com/AnacondaRecipes/anaconda_prompt-feedstock/blob/main/README.md

extra:
  recipe-maintainers:
    - marcoesters
